language: python
sudo: required
dist: trusty
services: docker
osx_image: xcode6.4

env:
  global:
      - VERSION=2.4.0
      - ZIP_FILE=apache-beam-${VERSION}-python.zip
      - STAGING=https://dist.apache.org/repos/dist/dev/beam/${VERSION}/
      # Remember to edit appveyor.yml too
      - PLAT=x86_64

matrix:
  include:
    - os: osx
      language: generic
      python: "2.7"
#    - os: osx
#      language: generic
#      env:
#        - MB_PYTHON_VERSION=3.3
#    - os: osx
#      language: generic
#      env:
#        - MB_PYTHON_VERSION=3.4
#    - os: osx
#      language: generic
#      env:
#        - MB_PYTHON_VERSION=3.5
#    - os: osx
#      language: generic
#      env:
#        - MB_PYTHON_VERSION=3.6
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=2.6
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=2.6
#        - PLAT=i686
    - os: linux
      python: "2.7"
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=2.7
#        - UNICODE_WIDTH=16
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=2.7
#        - PLAT=i686
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=2.7
#        - PLAT=i686
#        - UNICODE_WIDTH=16
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.3
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.3
#        - PLAT=i686
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.4
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.4
#        - PLAT=i686
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.5
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.5
#        - PLAT=i686
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.6
#    - os: linux
#      env:
#        - MB_PYTHON_VERSION=3.6
#        - PLAT=i686

#before_install:
#    - |
#      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then # Install Miniconda
#        curl -s -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh;
#        bash miniconda.sh -b -p $HOME/miniconda && rm miniconda.sh;
#        export PATH="$HOME/miniconda/bin:$PATH"; hash -r;
#        #conda install --quiet --yes nomkl --file=test-requirements.txt --file=test-requirements-cpython.txt;
#      fi
#    - python -c 'import sys; print("Python %s" % (sys.version,))'
#    - pip install Cython

install:
    - wget $STAGING/$ZIP_FILE
#    - unzip $ZIP_FILE

script:
  - |
     if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       build-wheels-osx.sh;
     else
       docker pull $DOCKER_IMAGE;
       docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels-linux.sh;
       ls wheelhouse/;
     fi
#    - cd apache-beam-$VERSION
#    - python setup.py bdist_wheel
#    - ls -lh dist

#script:
#    - install_run $PLAT

after_success:
#    Upload wheels to Rackspace container
#    - pip install wheelhouse-uploader
#    - python -m wheelhouse_uploader upload --local-folder
#          ${TRAVIS_BUILD_DIR}/wheelhouse/
#          $UPLOAD_ARGS
#          $CONTAINER
